### ISSUE TITLE
`fetch` is not set

### ISSUE THREAD

**Issue by shortcuts** [bodinsamuel/renovate-automatic-branch#300]
hey, seems like there's an issue in the GitHub action. You can see it failing on our repository https://github.com/algolia/api-clients-automation/actions/runs/5976805607/job/16215445723 and this one for the same error https://github.com/bodinsamuel/renovate-automatic-branch/actions/runs/5976800130/job/16215428387

bisou 💓

**Comment by bodinsamuel** [comment]
Arg ! Thanks

**Comment by bodinsamuel** [comment]
Can you upgrade and try again please? ☺️

**Comment by shortcuts** [comment]
perfect (see [job](https://github.com/algolia/api-clients-automation/actions/runs/6046430277/job/16407996398)), thanks for the quick fix cutie 💓
